# Generated by Django 5.1.6 on 2026-08-03 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_oauth", "0005_user_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="custom_for_ucp",
            field=models.ForeignKey(
                blank=True,
                db_comment="If set, this Role is a customization scoped exclusively to this one admin_recruiter's UserCompanyProfile — used only when THEY create recruiter-type users for their company.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_roles",
                to="auth_oauth.usercompanyprofile",
            ),
        ),
    ]
