# Generated by Django 5.1.6 on 2026-08-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_oauth", "0007_backfill_role_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermission",
            name="record_scope",
            field=models.CharField(
                blank=True,
                choices=[("own", "Own"), ("all", "All"), ("shared", "Shared")],
                db_comment="Which rows this role+permission grants access to: own/all/shared.",
                default="own",
                max_length=50,
                null=True,
            ),
        ),
    ]
