# Generated by Django 5.1.6 on 2026-08-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_oauth", "0009_backfill_admin_recruiter_manage_user_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompanyProfileShareModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("write_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "create_uid",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "write_uid",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "create_ucp_id",
                    models.CharField(blank=True, editable=False, null=True),
                ),
                (
                    "write_ucp_id",
                    models.CharField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_ucp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_shares_as_target",
                        to="auth_oauth.usercompanyprofile",
                    ),
                ),
                (
                    "viewer_ucp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visibility_shares_as_viewer",
                        to="auth_oauth.usercompanyprofile",
                    ),
                ),
            ],
            options={
                "db_table": "user_company_profile_shares",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("target_ucp", "viewer_ucp"),
                        name="uniq_active_ucp_share",
                    )
                ],
            },
        ),
    ]
